# Explicit Runge-Kutta integrator
usr/lib/libcasadi_integrator_rk.so*

# Collocation integrator
usr/lib/libcasadi_integrator_collocation.so*

# Old (all-at-once) collocation integrator
usr/lib/libcasadi_integrator_oldcollocation.so*
usr/lib/libcasadi_implicitfunction_newton.so*
usr/lib/libcasadi_homotopynlpsolver_simple.so*

# SQPMethod -  A basic SQP method
usr/lib/libcasadi_nlpsolver_sqpmethod.so*

# SCPgen -  An implementation of Lifted Newton SQP
usr/lib/libcasadi_nlpsolver_scpgen.so*

# StabilizedSQP -  An implementation of Stabilized SQP
usr/lib/libcasadi_nlpsolver_stabilizedsqp.so*

usr/lib/libcasadi_dplesolver_simple.so*
usr/lib/libcasadi_dplesolver_condensing.so*
usr/lib/libcasadi_dplesolver_lifting.so*
usr/lib/libcasadi_dlesolver_simple.so*
usr/lib/libcasadi_lrdplesolver_lifting.so*
usr/lib/libcasadi_lrdlesolver_fixed_smith.so*
usr/lib/libcasadi_dlesolver_fixed_smith.so*
usr/lib/libcasadi_dplesolver_lrdple.so*
usr/lib/libcasadi_dlesolver_lrdle.so*
usr/lib/libcasadi_lrdlesolver_dle.so*
usr/lib/libcasadi_dlesolver_dple.so*
#usr/lib/libcasadi_lrdlesolver_lrdple.so*
usr/lib/libcasadi_lrdplesolver_dple.so*
usr/lib/libcasadi_clesolver_simple.so*

# Reformulations
usr/lib/libcasadi_qpsolver_nlp.so*
usr/lib/libcasadi_implicitfunction_nlp.so*
usr/lib/libcasadi_lpsolver_qp.so*
usr/lib/libcasadi_qpsolver_qcqp.so*
usr/lib/libcasadi_socpsolver_sdp.so*
usr/lib/libcasadi_stabilizedqpsolver_qp.so*
usr/lib/libcasadi_linearsolver_symbolicqr.so*

#if(WITH_CSPARSE)
usr/lib/libcasadi_qcqpsolver_socp.so*
usr/lib/libcasadi_sdqpsolver_sdp.so*
#endif()
